#
# .travis.yml - configuration file for the travis continuous integration service
#
# see http://about.travis-ci.org/docs/user/languages/php for more hints
#
language: php

php:
  - 5.5

services:
  #- mongodb
  #- memcache

before_script:
  # Composer (PHP dependency solver)
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-dist --no-interaction

  # X Virtual Frame Buffer
  #  - "export DISPLAY=:99.0"
  #  - "sh -e /etc/init.d/xvfb start"
  # Selenium
  #  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar"
  #  - "java -jar selenium-server-standalone-2.31.0.jar > /dev/null &"
  #  - sleep 5
  # Chrome Browser Engine
  #  - "wget http://chromedriver.googlecode.com/files/chromedriver_linux32_23.0.1240.0.zip && unzip chromedriver_linux32_23.0.1240.0.zip && sudo mv chromedriver /usr/bin"
  # Nginx
  #- "wget http://nginx.org/download/nginx-1.2.8.tar.gz && tar xvzf nginx-1.2.8.tar.gz && cd nginx-1.2.8"
  #- "./configure --with-http_ssl_module --with-http_stub_status_module"
  #- "sudo make && sudo make install && sudo cp /usr/local/nginx/sbin/nginx /usr/sbin/ && sudo mkdir /var/log/nginx/ && sudo useradd nginx"
  #- wget config nginx.conf && cp
  #- sudo nginx -c tests/travis/nginx.conf -p "$PWD/"
  #- sleep 3

script:
#  - ./bin/behat --config application/tests/behat.yml  # run behat
   - phpunit -c ./tests/phpunit.xml.travis             # run phpunit

notifications:
  irc: "irc.freenode.org#koch"
  email: false

# reduce commit history of git checkout
git:
  depth: 1
